// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcIAkyONuqmogDALQbYfMh4YfgC9dtAtE',
    appId: '1:359624070923:web:7771eed65f33500e07340e',
    messagingSenderId: '359624070923',
    projectId: 'smatpay-87c59',
    authDomain: 'smatpay-87c59.firebaseapp.com',
    storageBucket: 'smatpay-87c59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRIuZlsWbrA15Nhpd0DUeqtKSxhljs-j4',
    appId: '1:359624070923:android:45e44424133652fb07340e',
    messagingSenderId: '359624070923',
    projectId: 'smatpay-87c59',
    storageBucket: 'smatpay-87c59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYidIHD8BK2On-Vf5pubjGrw2FnnmiThM',
    appId: '1:359624070923:ios:37cf06e98129559807340e',
    messagingSenderId: '359624070923',
    projectId: 'smatpay-87c59',
    storageBucket: 'smatpay-87c59.appspot.com',
    androidClientId: '359624070923-rlmomlln13g4q5e4ldcnt58q66trt8ij.apps.googleusercontent.com',
    iosClientId: '359624070923-94826mshldl8qq1bgpo37dkr3ufqfl4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.smatpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYidIHD8BK2On-Vf5pubjGrw2FnnmiThM',
    appId: '1:359624070923:ios:37cf06e98129559807340e',
    messagingSenderId: '359624070923',
    projectId: 'smatpay-87c59',
    storageBucket: 'smatpay-87c59.appspot.com',
    androidClientId: '359624070923-rlmomlln13g4q5e4ldcnt58q66trt8ij.apps.googleusercontent.com',
    iosClientId: '359624070923-94826mshldl8qq1bgpo37dkr3ufqfl4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.smatpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcIAkyONuqmogDALQbYfMh4YfgC9dtAtE',
    appId: '1:359624070923:web:a55cf11e7388028107340e',
    messagingSenderId: '359624070923',
    projectId: 'smatpay-87c59',
    authDomain: 'smatpay-87c59.firebaseapp.com',
    storageBucket: 'smatpay-87c59.appspot.com',
  );

}